apiVersion: batch/v1
kind: Job
metadata:
    name: agents-job

spec:
    parallelism: 10
    template:
        metadata:
          labels:
            app: agents-v1
        spec:
            containers:
            - name: agents-v1
              image: 146702968486.dkr.ecr.us-east-1.amazonaws.com/agents/agents
              env:
              - name: MODE
                value: "agents"
              - name: ARG2
                value: "nvq"
              - name: ARG3
                value: "gpu"
              - name: ARG4
                value: "agents_prod_v6"
              - name: ARG5
                value: "Tip_detect_prod_v1"
            restartPolicy: Never